name: test-deploy

# Run on each push to master
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_redoc:
    runs-on: ubuntu-latest
    name: Build redoc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build doc
        run: npx redoc-cli bundle https://bitbucket.org/medicalinformatics/mainzelliste/raw/development/resources/Mainzelliste.OpenApi.Spec.yaml -o mainzelliste-api.yml
      - name: move index.html
        run: mv mainzelliste-api.html index.html
      # use the public name of the action
#      - name: redoc-cli test
#        uses: seeebiii/redoc-cli-github-action@v8
#        with:
#          args: 'bundle https://bitbucket.org/medicalinformatics/mainzelliste/raw/development/resources/Mainzelliste.OpenApi.Spec.yaml -o mainzelliste-api.yml'
#      - name: check result
#        run: |
#          ls -al
#          test -f mainzelliste-api.html || (echo "Missing mainzelliste-api.html from previous step." && exit 1)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_redoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
